### ISSUE TITLE
LiveCD GNOME-Problem eliminieren

### ISSUE THREAD

**Issue by rhoerbe** [identinetics/PVZDliveCD#6]
Freeze Problem eliminieren. 

Im gleichen Aufwaschen: 
- GNOME durch schlanken Display Manager ersetzen.
- Default start mit acpi=off,  alternative Konfig „save boot2 anbieten mit noapic nolapic vga=normal). 
- Autoupdates wegkonfigurieren

**Comment by geohas** [comment]
- ~~Freeze Problem eliminieren~~
- ~~GNOME durch schlanken Display Manager ersetzen~~
-  ~~Autoupdates wegkonfigurieren~~
- Default start mit acpi=off, alternative Konfig „save boot2 anbieten mit noapic nolapic vga=normal).

**Comment by rhoerbe** [comment]
-> LXDE
boot selection not implemented
